spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/fishdex
spring.datasource.username=fishdex
spring.datasource.password=fishdex123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true